<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FTP_Project.Gui/**" />
    <Compile Remove="FTP_Project.Wpf/**" />
    <EmbeddedResource Remove="FTP_Project.Gui/**" />
    <EmbeddedResource Remove="FTP_Project.Wpf/**" />
    <None Remove="FTP_Project.Gui/**" />
    <None Remove="FTP_Project.Wpf/**" />
  </ItemGroup>

</Project>